language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: lHeY0yY1ScaP4nOiLi4aIUXRhwvg7se4pBVu+usjBCDvlgbSeSP7krknYyFbcFTeSXrls3v73AgxZO85B/HDDM1f0WxZTNRuatMDMMleSlet04YNlALpF3T8shVs76F0FGAdF+L/8zcOdSUlGMghYNoNOA90AU8keyaLrOXAbVPWPF4UYyAKzU5skJhlHNCL7BVMyKPV/azmL3y5glGjHS3H/tvv8sd7i0yftuAjX58ioIRpIXlwGkLE6fKP6QRoawVbjNdt0R05+dBK65r96rRhnPYsB9qm0KsEbocnW9HoD21rc1a+47GlbOYVR6VNHOslyog6wQ6AIEF1ewBfOzxcX6jdYc71saak+yQ2y+IJNn0hIojkMk7EE8lSlU9DzLE7apkvZzY+nXloK+uMoEkws0BzJww+D5Szn0ZIjApLLZTRhUvXrSRepD2Y6SOAwJAUNigOIBuHmIJdzwuh6ryrxm1tg2bcTyyi5EUwcienoL3iEMrsmY4UfAMcIx9mC25D7raqmOyiHJrcu4GnQp142c6A4Sg3wYGQxklWZrZGlB6NWKl/ptOPtYTF7YdejZBepwFhcEdbOCf8p7LMksQg5FtaN7ZPkBBEIUtlnIzJeFMVPuNGmmd4wkfyH4lyNvoh7uTDp9RKq6QheU+elO9+BPWcGj4pX6EBclGd7wY=
  app: portfolioV3
  on:
    repo: JTHUTCH94/portfolioV3
